development:
  adapter: mysql2
  encoding: utf8
  database: habits
  host: localhost
  username: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  database: habits_test
  host: localhost
  username: root
  password:
  pool: 5
  timeout: 5000

